### ISSUE TITLE
Show context menu on folders too

### ISSUE THREAD

**Issue by madskristensen** [fbmnds/TwinExplorer#1]
### Installed product versions
- Visual Studio: 2015 Professional
- This extension: 1.0.1

### Description
The context menu only shows up on files - not folders.

### Steps to recreate
1. Select 2 folders in Solution Explorer
2. Right-click

### Current behavior
The command button isn't showing up

### Expected behavior
The command button should show up

To fix this, you can add this to the .vsct file on line 74 as a direct child of the `<CommandTable>` element:

```xml
<CommandPlacements>
    <CommandPlacement guid="guidTwinExplorerCommandPackageCmdSet" id="MyMenuGroup" priority="0x0300">
        <Parent guid="guidSHLMainMenu" id="IDM_VS_CTXT_FOLDERNODE"/>
    </CommandPlacement>
</CommandPlacements>
```

**Comment by fbmnds** [comment]
almost done - it does fix it if select folders only. But if I select a file and a folder, I get another type of file context menu.
